name: deploy-payments

on: 
  push: 
    branches:
      - master
    paths:
      - 'payments/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd payments && docker build -f Dockerfile.prod -t liked95/payments .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push liked95/payments
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save sonny-ticket-prod-clusters
      - run: kubectl rollout restart deployment payments-depl
    
