name: deploy-manifests

on: 
  push: 
    branches:
      - master
    paths:
      - 'infra/kustomize/base/**'
      - 'infra/kustomize/overlays/prod/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save sonny-ticket-prod-clusters
      - run: kubectl apply -k infra/kustomize/overlays/prod
    
